name: codon_analyzer
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
dependencies:
  - python=3.8
  - snakemake=7.18.2
  - numpy=1.21
  - pandas=1.3
  - scipy=1.7
  - matplotlib=3.4
  - seaborn=0.11
  - scikit-learn=1.0
  - biopython=1.79
  - pybedtools=0.9
  - pysam=0.17
  - h5py=3.6
  - tqdm=4.62
  - click=8.0
  - pyyaml=6.0
  - jinja2=3.0
  - markdown=3.3
  - star=2.7.10b
  - hisat2=2.2.1
  - samtools=1.14
  - bedtools=2.30
  - stringtie=2.2.1
  - gffread=0.12.7
  - fastqc=0.11.9
  - multiqc=1.12
  - trimmomatic=0.39
  - bwa=0.7.17
  - bowtie2=2.4.4
  - r-base=4.1
  - r-essentials=4.1
  - r-tidyverse=1.3
  - r-ggplot2=3.3
  - r-dplyr=1.0
  - r-tidyr=1.1
  - r-pheatmap=1.0
  - r-ggdendro=0.1
  - r-corrplot=0.9
  - r-plotly=4.10
  - r-pca3d=0.1
  - r-knitr=1.37
  - r-rmarkdown=2.13
  - pip
  - pip:
    - pyfastx==0.8.4
    - codon-usage==1.0.0